export const SERVICE_CATEGORIES = [
  "Electrician",
  "Plumber",
  "Carpenter",
  "Painter",
  "AC Repair",
  "Cleaning",
  "Appliance Repair",
  "Home Cleaning",
  "Pest Control",
  "Gardening",
  "Interior Design",
  "CCTV Installation",
  "Water Purifier Repair",
  "RO Service",
  "Packers & Movers",
  "Laptop Repair",
  "Computer Repair",
  "Salon",
];